# Nombre de la aplicación en el ecosistema Spring Boot.
# Se utiliza para identificar este servicio en logs, métricas y registros de servicios.
spring.application.name=fyndr

spring.datasource.url=jdbc:mysql://localhost:3306/fyndr_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# create, create-drop, update, validate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true